### ISSUE TITLE
Memoize causes fetching the same configured instance on several EC2 creations

### ISSUE THREAD

**Issue by davidpelayo** [CascadeEnergy/aws-promised#12]
I was having this issue yesterday: http://stackoverflow.com/questions/32015345/data-returned-from-promises-with-aws-sdk-for-node-and-bluebird

And finally I found out what was causing it.

It may be that I don't understand properly why memoize is being used here, but, from what I understood, if I create an EC2-promised instance with a concrete configuration, like follows:

`var AWS = require('aws-promised'),
      ec2 = AWS.ec2({region: 'us-east-1'});`

If later on I need to create new EC2 instances with different regions configurations, simply because I could maybe request data per each region, by having memoize there what I get is a new instance with the previous configuration, which is wrong.

By commenting out the memoization on this file: https://github.com/davidpelayo/aws-promised/blob/master/ecs.js at the end, I get the expected results, as posted in the stackoverflow issue.

Could you elaborate why this would be happening, why memoize would be needed here and what the alternatives would be to solve my issues if there is any?

Thanks in advance.

**Comment by davidpelayo** [comment]
I found out a way of requesting addresses of different regions without creating a new EC2 object. In other words, by reusing the existing EC2 instance, by switching the endpoint like follows:

``` javascript
_.forEach(data.Regions, function (region) {
    //var ec2Addresses = AWS.ec2(
    //  {
    //    region: region.RegionName,
    //    endpoint: region.Endpoint
    //  }
    //);
    var ep = new AWS.Endpoint(region.Endpoint);
    ec2.config.region = region.RegionName;
    ec2.endpoint = ep;
    addressesPromises.push(ec2.describeAddressesPromised());
  });
  logger.info('About to fetch addresses per region');
```

Still, what if I would want and need to create different EC2 objects with the memoize there?

**Comment by nackjicholson** [comment]
I don't fully understand everything you're trying to do, but the `memoize` is there to prevent creation of multiple instances of the client unnecessarily. So when you create an `ec2` instance configured with `region: 'us-east-1'` if you try to create another instance which is exactly the same, you'll get the memoized/cached instance.

**Comment by nackjicholson** [comment]
Sorry, I accidentally hit comment before I was done with that thought.

If you have a situation where you need to change to a different region, I think what I would do is make a new `ec2` configured with `region: 'us-west-2'`. The way you've solved it above by digging into `config.region` and `endpoint` seems fine as well.

Do you need us to fix anything here? Would not memoizing have made this any easier on you? I'm willing to consider taking out memoization ( it wasn't my idea in the first place :) ).

Please close the issue unless there's further work we can do. If I don't hear from you I'll probably close it after a while. Thanks for bringing this up, it helps to get some feedback on your use of the module.

**Comment by davidpelayo** [comment]
The solution I provided was fine enough, eventually.

**Comment by nackjicholson** [comment]
Glad to hear it, thanks for providing it!
