### ISSUE TITLE
Approach to promisifyAll?

### ISSUE THREAD

**Issue by petemounce** [CascadeEnergy/aws-promised#29]
I discovered https://github.com/bazaarvoice/aws-cfn-custom-resource/blob/master/lib/aws.js just now. Relevant/pertinent to get aws-promised to all services without needing a file per service?

**Comment by jinsyaoommen** [comment]
AWS SDK supports promises now, and so we are not going to do any maintenance on this library. Please take a look at https://blogs.aws.amazon.com/javascript/post/Tx3BZ2DC4XARUGG/Support-for-Promises-in-the-SDK for more details.
