### ISSUE TITLE
Found docs which suggest aws-sdk supports the promise API.

### ISSUE THREAD

**Issue by nackjicholson** [CascadeEnergy/aws-promised#43]
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-making-requests.html

@jinsyaoommen I'm not sure if you are already aware of this, but at the bottom of that page there's a description of how to make a request using a promise when they're supported either natively, or you provide a polyfill module such as bluebird.

I haven't actually confirmed that it works, just found those docs. I have doubts that it's supported fully for all the aws-sdk clients.

If promises are supported by aws-sdk and anyone gets it to work, it could be a reason to put up a notice of deprecation or abandon support for this module.

**Comment by jinsyaoommen** [comment]
@nackjicholson - I recently became aware of it and used the s3 api and it worked. I'll test a few other api requests and make sure it works and then put up a notice for the package.

**Comment by jinsyaoommen** [comment]
@nackjicholson - deprecated the package.
